### ISSUE TITLE
Poplar1 aggregation parameters reveal information about submitted measurements

### ISSUE THREAD

**Issue by branlwyd** [cfrg/draft-irtf-cfrg-vdaf#109]
I believe that Poplar1 aggregation values are sensitive in the sense that they are prefixes of the most common values reported by clients. This makes them the only data exposed to aggregators which directly reveals information about the set of measurements being aggregated.

Assuming the above is accurate, I think it would be nicer if the aggregators were not exposed to measurement information. Would this be a realistically feasible change?

(edit: this fell out of discussion on https://github.com/divviup/janus/pull/417)

**Comment by cjpatton** [comment]
Unfortunately this problem is inherent to the construction. See the "Limitations" subsection from the intro of [the paper](https://eprint.iacr.org/2021/017.pdf).

It's possible that there is a different VDAF that doesn't have this issue, but we don't have one today.

[STAR](https://datatracker.ietf.org/doc/draft-dss-star/) is an alternative to DAP/Poplar1 for computing heavy hitters. It doesn't have the problem of leaking intermediate data to Aggregators, however the trust model is different.

**Comment by branlwyd** [comment]
OK, given that this is a known limitation of poplar1, I don't think leaving an open-but-unresolved/unresolvable issue around is useful. A different VDAF would be nice, but that is a far larger change (and wouldn't be tracked through this issue anyway).
