### ISSUE TITLE
VDAF for quantiles?

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#12]
With `prio3` it's straightforward to roughly estimate quantiles using a histogram (cf https://docs.rs/prio/0.6.1/prio/vdaf/prio3/type.Prio3Histogram64.html). But what if you wanted to precisely compute, say, the 50th percentile (i.e., the median) or the 95th percentile? Prio isn't well-suited for this (cf [[CGB17], Appendix G]).

If your application allows for multiple rounds of interaction with the clients, maybe you could do a kind of binary search to find the quantile you're after. Suppose the client measurements are arbitrary 32-bit integers and you want to compute the median. Suppose there are `N` measurements in all. Let `buckets = [2^31]`. Have the clients shard their measurements using `buckets` as the bucket boundaries. Execute the VDAF over the set of input shares, getting bucket counts `agg` as the aggregate result. `agg[0]` is equal to the number of measurements less than or equal to `2^31`, and `agg[1] <= N/2`, then the median must be less than `2^31`. On the other hand, if `agg[1] > N/2` then you know the median must greater than `2^31`. You then repeat the process, adjusting the bucket boundaries based on the previous result: if the median is less than `2^31`, then let `buckets = [2^31 - 2^30]`; otherwise let `buckets = [2^31 + 2^30]`.

I'm not sure how many iterations would be needed, or how precisely you could compute quantiles this way. Regardless, ideally there would be a VDAF that allows for computing quantiles without interacting with clients more than once.

[CGB17]: https://crypto.stanford.edu/prio/paper.pdf

**Comment by divergentdave** [comment]
In addition to histograms, Prio3 could be used to estimate quantiles by constructing a CountMin sketch. (See section 5.1 here https://dsf.berkeley.edu/cs286/papers/countmin-latin2004.pdf) I think this would also require some tuning based on expected measurement ranges and precision. The underlying FLP validity condition would be equivalent to running multiple independent histograms.

Poplar1 could be used to exactly compute quantiles, at a higher computational cost. Assuming the measurements are already integers, you could directly shard the measurements with Poplar1, and then run the Poplar1 aggregation process several times with a new tree-walking algorithm to arrive at the quantile. This algorithm would do a binary search to find the tree node where the number of measurements to the left, divided by the total number of measurements, is the closest to the target quantile level.

**Comment by cjpatton** [comment]
Hey @divergentdave, what do you think about resolving this issue by describing how to use Poplar1 for quantilies in the draft?

**Comment by divergentdave** [comment]
Sure, that sounds good. We could lay out how to use Poplar1 for each of chosen prefixes, heavy hitters, and quantiles.

**Comment by cjpatton** [comment]
Great. I'll label this "editorial" and assign it to you. Take your time ... we don't need needs this for 05.

**Comment by divergentdave** [comment]
Thinking about this some more, the algorithm described above would go against what I wrote in #273, because it would rely on prefix counts from inner tree nodes, and never check some of them all the way down to the leaf node. This would leave us with significantly worse robustness bounds for this application.

Here's an example of what the quantile algorithm would query and receive as it traverses a small tree, looking for the median.

```mermaid
graph
root[root\ncount: 187]
root --> 0 & 1
0[0\ncount: 115]
1[1\ncount: 72]
0 --> 00 & 01
1 --> 10 & 11
00[00\ncount: 50]
01[01\ncount: 65]
00 --> 000 & 001
01 --> 010 & 011
10 --> 100 & 101
11 --> 110 & 111
010[010\ncount: 39]
011[011\ncount: 26\nMedian]
```

To sharpen my description of the algorithm above, we know this is the median measurement because the count of all measurements less than or equal to 0b011 is greater than 50% of the total, and the count of all measurements greater than or equal to 0b011 is greater than 100% - 50% = 50% of the total. We get 50 + 39 + 26 > 187 / 2, and 26 + 72 > 187 / 2.

In this example, we only evaluated two nodes at the leaf level of the tree. Unlike with the heavy hitters algorithm, prefix counts from inner nodes do get used in determining the final quantile result -- an attack on extractability with the smaller field elements could do worse than merely trick us into adding more candidate prefixes to explore. With heavy hitters, the leaf level offers a chance to identify and reject dishonestly generated reports. For sufficiently high precision integer measurements, it would be impractical to evaluate every possible measurement at the leaf level of the tree.

With all that said, the quantile tree walking algorithm could work well with Mastic, since the concrete security of the robustness property doesn't depend so drastically on the tree level. Perhaps we should just write up the "heavy hitters" and "chosen prefixes" modes of operation in this draft for now, and leave it at that.

**Comment by cjpatton** [comment]
Thanks for the analysis here, @divergentdave. This issue is no longer purely editorial, since resolving it probably requires a warning for Popplar1. On the other hand, it seems like we should be able to use Mastic for this use case without running into the same extractability issue (https://github.com/jimouris/draft-mouris-cfrg-mastic/issues/53).

**Comment by divergentdave** [comment]
For completeness, here's another route to computing exact quantiles. There are constructions for "distributed comparison functions", akin to DPFs, but with an additional control bit and a different invariant at each node. This provides a function secret sharing scheme for $f_\alpha(x)=\left\\{ { 0, x < \alpha \atop 1, x \ge \alpha } \right .$ with compact keys. If each client uses its measurement as $\alpha$ and generates a pair of DCF keys, then aggregators can evaluate all DCFs at a series of trial values, and determine how many measurements are above and below that point. Thus, with multiple collections, they can do a binary search for any quantile, and the leakage function is a sequence of other quantiles that were not of interest. This would need to be paired with another primitive to verify that the output of each DCF is secret shares of zero or one. Poplar's secure sketching would not be sufficient, because the client provides single-use correlated randomness, and the same DCF needs to be evaluated multiple times. Using a FLPCP as in Doplar and Mastic would likely suffice. The overall computation cost would be $O(n^2 C)$, where $n$ is the bit length of the measured value and $C$ is the number of clients.
