### ISSUE TITLE
Distinguish between PRGs and Random Oracles

### ISSUE THREAD

**Issue by schoppmp** [cfrg/draft-irtf-cfrg-vdaf#159]
We currently have a single Prg interface, but we use it in places where either a PRG (in the cryptographic sense) or a Random Oracle is required. We should make clear which of these we need where.

**Comment by cjpatton** [comment]
One potential solution is to dump the `Prg` API altogether and just hard-code SHA-3 in Prio3 and Poplar1 verification (we will have something else for IDPF; see #32). I think @bifurcation suggested this route might make sense? If SHA-3 is "good enough", then perhaps we don't need agility?

**Comment by schoppmp** [comment]
Eventually hard-coding would make sense, yes. Should we make an effort though to limit it to where we actually need a random oracle? For example, the Prio version from ENPA uses an [AES-CTR based PRG](https://github.com/google/libprio-cc/tree/master/prio/prng), and I'm not sure if a random oracle / an XOF is actually needed there. Same for the places where we essentially extend a short random seed to a longer pseudorandom string.

**Comment by cjpatton** [comment]
Ideally we would -- admittedly our analysis in {{DPRS23}} is a bit heavy-handed with ROs :)

I think the right way to prioritize changes here is based on performance evaluation. From what I've seen so far (see https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/106) it seems like the cost of SHA-3 over AES for Prio3 is negligible. This makes sense because the cost is dominated by FF arithmetic, not the PRG. My hunch is that the same is true for ENPA-Prio (aka [Prio2](https://github.com/divviup/libprio-rs/blob/main/src/vdaf/prio2.rs)), but I haven't actually looked closely at this.
