### ISSUE TITLE
Combined state machine and output extraction

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-vdaf#45]
Right now, `prep_next` returns one of two types: a final output share, or a new state and output message. Why not split these two into separate functions, e.g., `prep_next` for advancing the state machine and then `prep_finish` for producing the final output?

**Comment by cjpatton** [comment]
We had this separation at some point, then decided to merge them into the same function. IIRC the thinking was that a particular VDAF might have a variable number of rounds, where the number of rounds depends on the inputs to the preparation phase. In this case the user would not know whether it should call `prep_next` or `prep_finish` at a particular step.

The VDAFs we have so far are all constant-round, and I think we're unlikely to have such a variable-round VDAF in the future. However, there are ways to extend your suggestion to allow the user to check if the current round is the last.

I would be in favor the change you suggest, since it reduces a bit of API complexity. However, note that this complexity is, arguably, inherent to the pseudocode and is not shared by languages like Rust that have rich enum support. E.g.: 
https://github.com/divviup/libprio-rs/blob/main/src/vdaf.rs#L223.) 

Thoughts, @schoppmp and @bifurcation?

**Comment by tgeoghegan** [comment]
To pile onto cjpatton's point: when we had a distinct `prepare_finish` method in `libprio`, we found that all it did was introduce the possibility of disagreement between client's tracking of the round of the prepare protocol we're on (which it has to do in order to choose whether to call `prepare_next` or `prepare_finish`) and `libprio`'s tracking of the round (which is encoded into the prepare state for all the VDAFs we've got). So `libprio` had to write extra code to handle `prepare_finish` being called at the wrong time, and clients of `libprio` had to write extra code to handle having their `prepare_next` call being rejected.

Another possibility that absolves the client of the VDAF from tracking rounds is to add a method on prepare state so you can query whether you are on the last round, and then do:

```
if prepare_state.is_last_round() {
    let output_share = prepare_finish(prepare_state, messages);
} else {
    let (new_state, next_message) = prepare_next(prepare_state, messages);
}
```

**Comment by cjpatton** [comment]
As of this writing, preparation is now:
* prep_init() -> (prep_state, prep_share)
* prep_shares_to_prep(prep_shares) -> prep_msg
* prep_next(prep_state, prep_msg) -> (prep_state, prep_share) / out_share

Thus we still have the problem that @chris-wood pointed out: the output type of the last API call (either the next prep state or a completed output share) is ambiguous if there is a variable number of rounds. However this is still hypothetical, as all existing VDAFs have a constant number of rounds.

Nevertheless, it is arguably "cleaner" from an API perspective to add a method on `PrepState`, call it `is_finished()`, which returns a `bool` indicating whether the next call to `prep_next()` is the last. I"d be fine with this change, but we would need to make sure to actually use it somewhere, otherwise we'll just end up with code rot.

One way we could use it here is to modify `run_vdaf()` by replacing the `for`-loop with a `while` loop once all of the aggregators are finished. Personally, I think this would be messier than what we have.

I'm going to close this issue with no action. If someone wants to see a change here, please feel free to re-open and send a PR.
