### ISSUE TITLE
Prio3: Usage of nonce when Shard w/o joint randomness.

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-vdaf#528]
For Prio3: the Shard function ([`shard`](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf-13#section-7.2.1) ) in the case of no joint randomness does not make use of nonce at all. However, `shard` still requires to pass a nonce even if it is not used.

Later in the protocol, the same nonce is passed to `prep_init`.

Suggestion: if sharding uses one nonce per-measurement, would it be ok: 
 1) to generate the nonce internally by the Shard function, rather than receiving it from the caller?, and
 2) to store the nonce as part of the `public_share`?

**Comment by divergentdave** [comment]
I don't think it would make sense for sharding to produce the nonce, because we also expect the application to also make use of this nonce in its mitigations against replay attacks.

Prio3 without joint randomness doesn't need the nonce in part because it doesn't need the same random oracle model computational security assumptions as Prio3 with joint randomness. The only XOF calls in `shard_without_joint_rand()` are for the helper measurement share, helper proof share, and proof randomness. In each case, we are using the XOF as a PRG expanding a fresh random seed, so there's no need to mix in the application context or nonce, as the values would still be uniformly random.

**Comment by cjpatton** [comment]
@armfazh we're closing this because we don't think there's anything to do here. Feel free to re-open if you wanna continue discussion.
